import { randomUUID } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';

import express, { type RequestHandler, type Router } from 'express';
import { registerAppResource, registerAppTool, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import { z } from 'zod';

import type { AgentJob } from './agent-job-store.js';
import type { AgentService } from './agent-service.js';
import type { Item, ItemStore } from './item-store.js';
import type { WeatherResponse } from './weather-service.js';

// This is the shared application contract. It is intentionally imported rather
// than recreated here so Teams cards, the MCP widget, and the CopilotKit tab
// cannot silently drift apart. The shared file is supplied by the integration
// layer and is outside this subtask's write allow-list.
import type { GenUiEnvelopeV1 } from '../shared/genui.js';

export const MCP_GENUI_RESOURCE_URI = 'ui://teams-workspace/v1/genui.html';
export const MCP_GENUI_RESOURCE_MIME_TYPE = 'text/html;profile=mcp-app';

type WeatherLookup = (
  latitude: number,
  longitude: number,
  options?: { demo?: boolean },
) => Promise<WeatherResponse>;

type ItemStoreReader = Pick<ItemStore, 'list' | 'summary'>;
type AgentServiceReader = Pick<AgentService, 'get' | 'list' | 'countActive'>;

export interface McpGenUiDependencies {
  itemStore: ItemStoreReader;
  agentService: AgentServiceReader;
  getWeather: WeatherLookup;
}

export interface McpGenUiServerOptions extends McpGenUiDependencies {
  /** HTML generated by scripts/build-mcp-widget.mjs. */
  widgetHtml?: string | (() => string | Promise<string>);
  /** Defaults to dist/mcp-widget/index.html for the existing Express app. */
  widgetHtmlPath?: string;
  /** Stateful sessions are the default; stateless mode is useful for simple hosts. */
  sessionMode?: 'stateful' | 'stateless';
  /** Enable JSON responses instead of SSE where the MCP host requests it. */
  enableJsonResponse?: boolean;
  /** Optional server identity override for host diagnostics. */
  serverName?: string;
  serverVersion?: string;
  onSessionInitialized?: (sessionId: string) => void | Promise<void>;
  onSessionClosed?: (sessionId: string) => void | Promise<void>;
}

export interface McpGenUiServerInstance {
  server: McpServer;
  transport: StreamableHTTPServerTransport;
  ready: Promise<void>;
  close(): Promise<void>;
}

export type McpGenUiRouter = Router & {
  close(): Promise<void>;
};

type EnvelopeKind = 'task-list' | 'weather' | 'job-status' | 'result' | 'error';

type EnvelopeInput = {
  kind: EnvelopeKind;
  id: string;
  title: string;
  summary: string;
  sections: Array<Record<string, unknown>>;
  fallbackText: string;
  actions?: Array<Record<string, unknown>>;
  citations?: Array<Record<string, unknown>>;
  aiGenerated?: boolean;
  metadata?: Record<string, unknown>;
};

const envelopeSchema = z.object({
  kind: z.enum(['answer', 'weather', 'task-list', 'job-status', 'approval', 'result', 'error']),
  id: z.string().optional(),
  correlationId: z.string().optional(),
  title: z.string().optional(),
  summary: z.string().optional(),
  sections: z.array(z.record(z.unknown())).optional(),
  actions: z.array(z.record(z.unknown())).optional(),
  citations: z.array(z.record(z.unknown())).optional(),
  aiGenerated: z.boolean().optional(),
  fallbackText: z.string().optional(),
  status: z.enum(['loading', 'ready', 'empty', 'error', 'approval', 'complete']).optional(),
  metadata: z.record(z.unknown()).optional(),
}).passthrough();

const workspaceInputSchema = z.object({
  limit: z.number().int().min(1).max(20).optional(),
});

const weatherInputSchema = z.object({
  latitude: z.number().min(-90).max(90),
  longitude: z.number().min(-180).max(180),
  demo: z.boolean().optional(),
});

const jobInputSchema = z.object({
  jobId: z.string().min(1).optional(),
  limit: z.number().int().min(1).max(10).optional(),
});

const renderInputSchema = z.object({
  envelope: z.record(z.unknown()),
});

function clip(value: string | undefined, max = 1200): string | undefined {
  if (!value) return undefined;
  return value.length <= max ? value : `${value.slice(0, max)}\n(일부 생략됨)`;
}

function itemToSectionItem(item: Item): Record<string, unknown> {
  return { id: String(item.id), label: item.title, status: item.status };
}

function jobToSectionItem(job: AgentJob): Record<string, unknown> {
  return {
    id: job.id,
    label: job.prompt,
    status: job.status,
    progress: job.progress.slice(-4),
    finishedAt: job.finishedAt,
  };
}

function createEnvelope(input: EnvelopeInput): GenUiEnvelopeV1 {
  // The cast is deliberately limited to this boundary. The canonical type and
  // its validator live in src/shared/genui.ts; this adapter only maps existing
  // store/service data into that contract.
  return {
    kind: input.kind,
    id: input.id,
    correlationId: randomUUID(),
    title: input.title,
    summary: input.summary,
    sections: input.sections,
    actions: input.actions ?? [],
    citations: input.citations ?? [],
    aiGenerated: input.aiGenerated ?? false,
    fallbackText: input.fallbackText,
    ...(input.metadata ? { metadata: input.metadata } : {}),
    status: input.kind === 'result' ? 'complete' : input.kind === 'error' ? 'error' : 'ready',
  } as GenUiEnvelopeV1;
}

function resultForEnvelope(envelope: GenUiEnvelopeV1, text: string): CallToolResult {
  return {
    content: [{ type: 'text', text }],
    structuredContent: envelope as unknown as Record<string, unknown>,
  };
}

function fallbackTextOf(envelope: GenUiEnvelopeV1): string {
  const value = (envelope as unknown as Record<string, unknown>).fallbackText;
  return typeof value === 'string' ? value : '';
}

function errorResult(message: string): CallToolResult {
  return {
    isError: true,
    content: [{ type: 'text', text: message }],
  };
}

function workspaceEnvelope(deps: McpGenUiDependencies, limit = 8): GenUiEnvelopeV1 {
  const items = deps.itemStore.list();
  const summary = deps.itemStore.summary();
  const jobs = deps.agentService.list(limit);
  const openItems = items.filter((item) => item.status === 'open').slice(0, limit);
  const activeJobs = jobs.filter((job) =>
    job.status === 'queued' || job.status === 'running' || job.status === 'awaiting_approval',
  );

  const itemText = openItems.length === 0
    ? '진행 중인 업무가 없습니다.'
    : openItems.map((item) => `- ${item.title}`).join('\n');
  const jobText = jobs.length === 0
    ? '최근 Codex 작업이 없습니다.'
    : jobs.map((job) => `- ${job.id}: ${job.status}`).join('\n');

  return createEnvelope({
    kind: 'task-list',
    id: 'workspace-snapshot',
    title: 'Teams 업무 허브',
    summary: `업무 ${summary.total}개 · 진행 중 ${summary.open}개 · 완료 ${summary.done}개 · 활성 작업 ${activeJobs.length}개`,
    sections: [
      {
        type: 'stats',
        title: '업무 요약',
        fields: [
          { label: '전체', value: summary.total },
          { label: '진행 중', value: summary.open },
          { label: '완료', value: summary.done },
          { label: '활성 Codex', value: activeJobs.length },
        ],
      },
      {
        type: 'list',
        title: '진행 중인 업무',
        items: openItems.map(itemToSectionItem),
      },
      {
        type: 'list',
        title: '최근 Codex 작업',
        items: jobs.map(jobToSectionItem),
      },
    ],
    fallbackText: `${itemText}\n\n${jobText}`,
    metadata: { source: 'teams-workspace', deterministic: true },
  });
}

function weatherEnvelope(weather: WeatherResponse): GenUiEnvelopeV1 {
  const { current, location } = weather;
  return createEnvelope({
    kind: 'weather',
    id: `weather-${location.latitude.toFixed(4)}-${location.longitude.toFixed(4)}`,
    title: '현재 위치 날씨',
    summary: `${location.name} · ${current.temperature.toFixed(1)}°C · ${current.condition}`,
    sections: [
      {
        type: 'weather',
        location: location.name,
        latitude: location.latitude,
        longitude: location.longitude,
        timezone: location.timezone,
        temperature: current.temperature,
        apparentTemperature: current.apparentTemperature,
        humidity: current.humidity,
        windSpeed: current.windSpeed,
        precipitation: current.precipitation,
        condition: current.condition,
        icon: current.icon,
        source: weather.source,
        observedAt: current.time,
      },
    ],
    fallbackText: `${location.name}\n${current.temperature.toFixed(1)}°C · ${current.condition}\n체감 ${current.apparentTemperature.toFixed(1)}°C · 습도 ${Math.round(current.humidity)}% · 바람 ${current.windSpeed.toFixed(1)}km/h`,
    metadata: { source: weather.source, deterministic: true },
  });
}

function jobEnvelope(job: AgentJob | undefined, limit = 8): GenUiEnvelopeV1 {
  if (!job) {
    return createEnvelope({
      kind: 'job-status',
      id: 'job-status',
      title: 'Codex 작업 상태',
      summary: '요청한 작업을 찾을 수 없습니다.',
      sections: [{ type: 'status', status: 'not-found' }],
      fallbackText: '요청한 Codex 작업을 찾을 수 없습니다.',
      metadata: { source: 'teams-workspace', deterministic: true },
    });
  }

  const statusText = `작업 ${job.id}: ${job.status}`;
  return createEnvelope({
    kind: 'job-status',
    id: job.id,
    title: 'Codex 작업 상태',
    summary: statusText,
    sections: [
      {
        type: 'status',
        id: job.id,
        status: job.status,
        mode: job.mode,
        createdAt: job.createdAt,
        startedAt: job.startedAt,
        finishedAt: job.finishedAt,
        threadId: job.threadId,
        commitHash: job.commitHash,
        error: clip(job.error),
        result: clip(job.result),
      },
      {
        type: 'list',
        title: '최근 진행 기록',
        items: job.progress.slice(-limit).map((message, index) => ({
          id: `${job.id}-progress-${index}`,
          label: message,
        })),
      },
    ],
    fallbackText: [
      statusText,
      job.error,
      job.result,
      job.progress.length > 0 ? job.progress.slice(-limit).join('\n') : undefined,
    ].filter(Boolean).join('\n\n'),
    metadata: { source: 'teams-workspace', deterministic: true },
  });
}

function isEnvelope(value: unknown): value is GenUiEnvelopeV1 {
  return envelopeSchema.safeParse(value).success;
}

async function resolveWidgetHtml(options: McpGenUiServerOptions): Promise<string> {
  if (typeof options.widgetHtml === 'string') return options.widgetHtml;
  if (typeof options.widgetHtml === 'function') return await options.widgetHtml();

  const widgetPath = options.widgetHtmlPath ?? path.resolve(process.cwd(), 'dist/mcp-widget/index.html');
  try {
    return await fs.readFile(widgetPath, 'utf8');
  } catch (error) {
    const reason = error instanceof Error ? error.message : 'unknown error';
    throw new Error(`MCP GenUI 위젯 산출물을 찾을 수 없습니다: ${widgetPath} (${reason}). node scripts/build-mcp-widget.mjs를 먼저 실행하세요.`);
  }
}

function registerTools(server: McpServer, options: McpGenUiServerOptions): void {
  registerAppTool(
    server,
    'get_workspace_snapshot',
    {
      title: 'Get workspace snapshot',
      description: 'Use this when the user asks for the current Teams workspace tasks or active Codex jobs. This is a deterministic read-only data tool; it never invents an LLM answer.',
      inputSchema: workspaceInputSchema,
      outputSchema: envelopeSchema,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        openWorldHint: false,
        idempotentHint: true,
      },
      _meta: { ui: { visibility: ['model'] } },
    },
    async ({ limit }) => {
      const envelope = workspaceEnvelope(options, limit ?? 8);
      return resultForEnvelope(envelope, fallbackTextOf(envelope));
    },
  );

  registerAppTool(
    server,
    'get_weather',
    {
      title: 'Get weather',
      description: 'Use this when the user supplies device coordinates or explicitly provided coordinates and asks for current weather. Do not infer GPS, a city, or a default location in this tool.',
      inputSchema: weatherInputSchema,
      outputSchema: envelopeSchema,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        openWorldHint: true,
        idempotentHint: true,
      },
      _meta: { ui: { visibility: ['model'] } },
    },
    async ({ latitude, longitude, demo }) => {
      try {
        const weather = await options.getWeather(latitude, longitude, { demo });
        const envelope = weatherEnvelope(weather);
        return resultForEnvelope(envelope, fallbackTextOf(envelope));
      } catch (error) {
        const message = error instanceof Error ? error.message : '날씨 정보를 가져오지 못했습니다.';
        return errorResult(`날씨 조회에 실패했습니다. 위치와 네트워크를 확인하세요. (${message})`);
      }
    },
  );

  registerAppTool(
    server,
    'get_job_status',
    {
      title: 'Get Codex job status',
      description: 'Use this when the user asks for a Codex job status. If jobId is omitted, return a deterministic list of recent jobs.',
      inputSchema: jobInputSchema,
      outputSchema: envelopeSchema,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        openWorldHint: false,
        idempotentHint: true,
      },
      _meta: { ui: { visibility: ['model'] } },
    },
    async ({ jobId, limit }) => {
      const selected = jobId
        ? options.agentService.get(jobId)
        : options.agentService.list(limit ?? 8)[0];
      const envelope = jobEnvelope(selected, limit ?? 8);
      return resultForEnvelope(envelope, fallbackTextOf(envelope));
    },
  );

  registerAppTool(
    server,
    'render_workspace_response',
    {
      title: 'Render workspace response',
      description: 'Use this after a data tool has produced a GenUiEnvelopeV1 when the user needs the interactive MCP App view. It only renders supplied structured data and never calls an LLM or fetches hidden data.',
      inputSchema: renderInputSchema,
      outputSchema: envelopeSchema,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        openWorldHint: false,
        idempotentHint: true,
      },
      _meta: {
        ui: {
          resourceUri: MCP_GENUI_RESOURCE_URI,
          visibility: ['model'],
        },
      },
    },
    async ({ envelope }) => {
      if (!isEnvelope(envelope)) {
        return errorResult('render_workspace_response에는 유효한 GenUiEnvelopeV1이 필요합니다. 데이터 도구를 먼저 호출하세요.');
      }

      return resultForEnvelope(envelope, fallbackTextOf(envelope));
    },
  );
}

export function createMcpGenUiServer(options: McpGenUiServerOptions): McpGenUiServerInstance {
  const server = new McpServer(
    {
      name: options.serverName ?? 'teams-workspace-mcp',
      version: options.serverVersion ?? '1.0.0',
    },
    {
      instructions: 'This MCP App renders structured workspace data. It is not the Teams mobile iframe and cannot read Teams GPS directly.',
    },
  );

  registerTools(server, options);

  registerAppResource(
    server,
    'Teams Workspace GenUI',
    MCP_GENUI_RESOURCE_URI,
    {
      description: 'Portable MCP Apps widget for rendering GenUiEnvelopeV1. This resource is for MCP hosts such as ChatGPT or Codex, not the Teams mobile tab iframe.',
      mimeType: MCP_GENUI_RESOURCE_MIME_TYPE,
      _meta: {
        ui: {
          prefersBorder: false,
          csp: { connectDomains: [], resourceDomains: [] },
        },
      },
    },
    async (uri) => ({
      contents: [{
        uri: uri.toString(),
        mimeType: RESOURCE_MIME_TYPE,
        text: await resolveWidgetHtml(options),
        _meta: {
          ui: {
            prefersBorder: false,
            csp: { connectDomains: [], resourceDomains: [] },
          },
        },
      }],
    }),
  );

  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: options.sessionMode === 'stateless' ? undefined : () => randomUUID(),
    enableJsonResponse: options.enableJsonResponse,
    onsessioninitialized: options.onSessionInitialized,
    onsessionclosed: options.onSessionClosed,
  });
  const ready = server.connect(transport);

  return {
    server,
    transport,
    ready,
    async close(): Promise<void> {
      await transport.close().catch(() => undefined);
      await server.close().catch(() => undefined);
    },
  };
}

type Session = McpGenUiServerInstance;

export function createMcpGenUiHandler(options: McpGenUiServerOptions): RequestHandler & { close(): Promise<void> } {
  const sessions = new Map<string, Session>();
  const stateful = options.sessionMode !== 'stateless';
  const transientSessions = new Set<Session>();

  const close = async (): Promise<void> => {
    const current = [...sessions.values(), ...transientSessions];
    sessions.clear();
    transientSessions.clear();
    await Promise.all(current.map((session) => session.close()));
  };

  const handler: RequestHandler = async (request, response) => {
    const sessionId = request.header('mcp-session-id');
    let session = sessionId ? sessions.get(sessionId) : undefined;

    if (!session && request.method.toUpperCase() === 'POST') {
      let created: Session | undefined;
      const serverOptions: McpGenUiServerOptions = {
        ...options,
        onSessionInitialized: async (initializedId) => {
          if (created && stateful) {
            sessions.set(initializedId, created);
            transientSessions.delete(created);
          }
          await options.onSessionInitialized?.(initializedId);
        },
        onSessionClosed: async (closedId) => {
          sessions.delete(closedId);
          await options.onSessionClosed?.(closedId);
        },
      };
      created = createMcpGenUiServer(serverOptions);
      session = created;
      if (stateful) transientSessions.add(created);
      await created.ready;
    }

    if (!session) {
      response.status(sessionId ? 404 : 400).json({
        error: sessionId ? 'Unknown MCP session' : 'MCP session is required for this method',
      });
      return;
    }

    try {
      await session.transport.handleRequest(request, response, request.body);
      if (!stateful) await session.close();
    } catch (error) {
      if (!response.headersSent) {
        const message = error instanceof Error ? error.message : 'MCP request failed';
        response.status(500).json({ error: message });
      }
    } finally {
      if (stateful && sessionId) transientSessions.delete(session);
    }
  };

  return Object.assign(handler, { close });
}

export function createMcpGenUiRouter(options: McpGenUiServerOptions): McpGenUiRouter {
  const router = express.Router() as McpGenUiRouter;
  const handler = createMcpGenUiHandler(options);
  router.use(express.json({ limit: '1mb' }));
  router.all('/', handler);
  router.close = handler.close;
  return router;
}
