import { randomUUID } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';

import express, { type RequestHandler, type Router } from 'express';
import { registerAppResource, registerAppTool, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import { z } from 'zod';

import type { AgentJob } from './agent-job-store.js';
import type { AgentService } from './agent-service.js';
import type { Item, ItemStore } from './item-store.js';
import type { WeatherResponse } from './weather-service.js';

// This is the shared application contract. It is intentionally imported rather
// than recreated here so Teams cards, the MCP widget, and the CopilotKit tab
// cannot silently drift apart. The shared file is supplied by the integration
// layer and is outside this subtask's write allow-list.
import {
  GENUI_SCHEMA_VERSION,
  GenUiEnvelopeV1BaseSchema,
  GenUiEnvelopeV1Schema,
  type GenUiEnvelopeV1,
  type GenUiKind,
  type GenUiState,
} from '../shared/genui.js';

export const MCP_GENUI_RESOURCE_URI = 'ui://teams-workspace/v1/genui.html';
export const MCP_GENUI_RESOURCE_MIME_TYPE = 'text/html;profile=mcp-app';

type WeatherLookup = (
  latitude: number,
  longitude: number,
  options?: { demo?: boolean },
) => Promise<WeatherResponse>;

type ItemStoreReader = Pick<ItemStore, 'list' | 'summary'>;
// MCP is still an explicitly local-only reader in this slice. Its route is
// disabled by default in production; the next security slice must remove the
// unauthenticated opt-in before exposing it publicly.
type AgentServiceReader = Pick<AgentService, 'getLocalOnly' | 'listLocalOnly' | 'countActiveLocalOnly'>;

export interface McpGenUiDependencies {
  itemStore: ItemStoreReader;
  agentService: AgentServiceReader;
  getWeather: WeatherLookup;
}

export interface McpGenUiServerOptions extends McpGenUiDependencies {
  /** HTML generated by scripts/build-mcp-widget.mjs. */
  widgetHtml?: string | (() => string | Promise<string>);
  /** Defaults to dist/mcp-widget/index.html for the existing Express app. */
  widgetHtmlPath?: string;
  /** Stateful sessions are the default; stateless mode is useful for simple hosts. */
  sessionMode?: 'stateful' | 'stateless';
  /** Enable JSON responses instead of SSE where the MCP host requests it. */
  enableJsonResponse?: boolean;
  /** Optional server identity override for host diagnostics. */
  serverName?: string;
  serverVersion?: string;
  /** Maximum idle time for a stateful MCP session. Defaults to ten minutes. */
  sessionTtlMs?: number;
  /** Maximum number of mapped or initializing stateful sessions. Defaults to 64. */
  maxSessions?: number;
  /** Optional stateful-session sweep interval. Defaults to at most one minute. */
  sessionSweepIntervalMs?: number;
  onSessionInitialized?: (sessionId: string) => void | Promise<void>;
  onSessionClosed?: (sessionId: string) => void | Promise<void>;
}

export interface McpGenUiServerInstance {
  server: McpServer;
  transport: StreamableHTTPServerTransport;
  ready: Promise<void>;
  close(): Promise<void>;
}

export type McpGenUiRouter = Router & {
  close(): Promise<void>;
};

type EnvelopeKind = Extract<GenUiKind, 'task-list' | 'weather' | 'job-status' | 'result' | 'error'>;

type EnvelopeInput = {
  kind: EnvelopeKind;
  id: string;
  title?: string;
  summary?: string;
  sections: Array<Record<string, unknown>>;
  fallbackText?: string;
  actions?: Array<Record<string, unknown>>;
  citations?: Array<Record<string, unknown>>;
  aiGenerated?: boolean;
  metadata?: Record<string, unknown>;
  status?: GenUiState;
};

const workspaceInputSchema = z.object({
  limit: z.number().int().min(1).max(20).optional(),
});

const weatherInputSchema = z.object({
  latitude: z.number().min(-90).max(90),
  longitude: z.number().min(-180).max(180),
  demo: z.boolean().optional(),
});

const jobInputSchema = z.object({
  jobId: z.string().min(1).optional(),
  limit: z.number().int().min(1).max(10).optional(),
});

const renderInputSchema = z.object({
  envelope: z.record(z.unknown()),
});

function clip(value: string | undefined, max = 1200): string | undefined {
  if (!value) return undefined;
  return value.length <= max ? value : `${value.slice(0, max)}\n(일부 생략됨)`;
}

function itemToSectionItem(item: Item): Record<string, unknown> {
  return { id: String(item.id), label: item.title, status: item.status };
}

function jobToSectionItem(job: AgentJob): Record<string, unknown> {
  return {
    id: job.id,
    label: job.prompt,
    status: job.status,
    description: job.finishedAt ? `완료 시각: ${job.finishedAt}` : undefined,
  };
}

function createEnvelope(input: EnvelopeInput): GenUiEnvelopeV1 {
  return GenUiEnvelopeV1Schema.parse({
    schemaVersion: GENUI_SCHEMA_VERSION,
    kind: input.kind,
    id: input.id,
    correlationId: randomUUID(),
    status: input.status ?? (input.kind === 'result' ? 'complete' : input.kind === 'error' ? 'error' : 'ready'),
    title: input.title,
    summary: input.summary,
    sections: input.sections,
    actions: input.actions ?? [],
    citations: input.citations ?? [],
    aiGenerated: input.aiGenerated ?? false,
    fallbackText: input.fallbackText,
    ...(input.metadata ? { metadata: input.metadata } : {}),
  });
}

function resultForEnvelope(envelope: GenUiEnvelopeV1, text: string): CallToolResult {
  const parsed = GenUiEnvelopeV1Schema.parse(envelope);
  return {
    content: [{ type: 'text', text }],
    structuredContent: Object.fromEntries(Object.entries(parsed)),
  };
}

function fallbackTextOf(envelope: GenUiEnvelopeV1): string {
  return envelope.fallbackText ?? '';
}

function errorResult(message: string): CallToolResult {
  const envelope = createEnvelope({
    kind: 'error',
    id: 'mcp-error',
    title: 'MCP GenUI 오류',
    summary: message,
    sections: [{ type: 'status', label: '오류', status: 'error', description: message }],
    fallbackText: message,
    status: 'error',
    metadata: { source: 'mcp', deterministic: true },
  });
  return { ...resultForEnvelope(envelope, message), isError: true };
}

function workspaceEnvelope(deps: McpGenUiDependencies, limit = 8): GenUiEnvelopeV1 {
  const items = deps.itemStore.list();
  const summary = deps.itemStore.summary();
  const jobs = deps.agentService.listLocalOnly(limit);
  const openItems = items.filter((item) => item.status === 'open').slice(0, limit);
  const activeJobs = jobs.filter((job) =>
    job.status === 'queued' || job.status === 'running' || job.status === 'awaiting_approval',
  );

  const itemText = openItems.length === 0
    ? '진행 중인 업무가 없습니다.'
    : openItems.map((item) => `- ${item.title}`).join('\n');
  const jobText = jobs.length === 0
    ? '최근 Codex 작업이 없습니다.'
    : jobs.map((job) => `- ${job.id}: ${job.status}`).join('\n');

  return createEnvelope({
    kind: 'task-list',
    id: 'workspace-snapshot',
    title: 'Teams 업무 허브',
    summary: `업무 ${summary.total}개 · 진행 중 ${summary.open}개 · 완료 ${summary.done}개 · 활성 작업 ${activeJobs.length}개`,
    sections: [
      {
        type: 'stats',
        title: '업무 요약',
        stats: [
          { label: '전체', value: summary.total },
          { label: '진행 중', value: summary.open },
          { label: '완료', value: summary.done },
          { label: '활성 Codex', value: activeJobs.length },
        ],
      },
      {
        type: 'list',
        title: '진행 중인 업무',
        items: openItems.map(itemToSectionItem),
      },
      {
        type: 'list',
        title: '최근 Codex 작업',
        items: jobs.map(jobToSectionItem),
      },
    ],
    fallbackText: `${itemText}\n\n${jobText}`,
    metadata: { source: 'teams-workspace', deterministic: true },
  });
}

function weatherEnvelope(weather: WeatherResponse): GenUiEnvelopeV1 {
  const { current, location } = weather;
  return createEnvelope({
    kind: 'weather',
    id: `weather-${location.latitude.toFixed(4)}-${location.longitude.toFixed(4)}`,
    title: '현재 위치 날씨',
    summary: `${location.name} · ${current.temperature.toFixed(1)}°C · ${current.condition}`,
    sections: [
      {
        type: 'weather',
        location: location.name,
        latitude: location.latitude,
        longitude: location.longitude,
        timezone: location.timezone,
        temperature: current.temperature,
        apparentTemperature: current.apparentTemperature,
        humidity: current.humidity,
        windSpeed: current.windSpeed,
        precipitation: current.precipitation,
        condition: current.condition,
        icon: current.icon,
        source: weather.source,
        observedAt: current.time,
      },
    ],
    fallbackText: `${location.name}\n${current.temperature.toFixed(1)}°C · ${current.condition}\n체감 ${current.apparentTemperature.toFixed(1)}°C · 습도 ${Math.round(current.humidity)}% · 바람 ${current.windSpeed.toFixed(1)}km/h`,
    metadata: { source: weather.source, deterministic: true },
  });
}

function jobEnvelope(job: AgentJob | undefined, limit = 8): GenUiEnvelopeV1 {
  if (!job) {
    return createEnvelope({
      kind: 'job-status',
      id: 'job-status',
      title: 'Codex 작업 상태',
      summary: '요청한 작업을 찾을 수 없습니다.',
      sections: [{ type: 'status', status: 'not-found' }],
      fallbackText: '요청한 Codex 작업을 찾을 수 없습니다.',
      metadata: { source: 'teams-workspace', deterministic: true },
    });
  }

  const statusText = `작업 ${job.id}: ${job.status}`;
  return createEnvelope({
    kind: 'job-status',
    id: job.id,
    title: 'Codex 작업 상태',
    summary: statusText,
    sections: [
      {
        type: 'status',
        status: job.status,
        description: [
          `모드: ${job.mode}`,
          `생성: ${job.createdAt}`,
          job.startedAt ? `시작: ${job.startedAt}` : undefined,
          job.finishedAt ? `완료: ${job.finishedAt}` : undefined,
          job.threadId ? `스레드: ${job.threadId}` : undefined,
          job.commitHash ? `커밋: ${job.commitHash}` : undefined,
          clip(job.error),
          clip(job.result),
        ].filter(Boolean).join('\n'),
      },
      {
        type: 'list',
        title: '최근 진행 기록',
        items: job.progress.slice(-limit).map((message, index) => ({
          id: `${job.id}-progress-${index}`,
          label: message,
        })),
      },
    ],
    fallbackText: [
      statusText,
      job.error,
      job.result,
      job.progress.length > 0 ? job.progress.slice(-limit).join('\n') : undefined,
    ].filter(Boolean).join('\n\n'),
    metadata: { source: 'teams-workspace', deterministic: true },
  });
}

async function resolveWidgetHtml(options: McpGenUiServerOptions): Promise<string> {
  if (typeof options.widgetHtml === 'string') return options.widgetHtml;
  if (typeof options.widgetHtml === 'function') return await options.widgetHtml();

  const widgetPath = options.widgetHtmlPath ?? path.resolve(process.cwd(), 'dist/mcp-widget/index.html');
  try {
    return await fs.readFile(widgetPath, 'utf8');
  } catch (error) {
    const reason = error instanceof Error ? error.message : 'unknown error';
    throw new Error(`MCP GenUI 위젯 산출물을 찾을 수 없습니다: ${widgetPath} (${reason}). node scripts/build-mcp-widget.mjs를 먼저 실행하세요.`);
  }
}

function registerTools(server: McpServer, options: McpGenUiServerOptions): void {
  registerAppTool(
    server,
    'get_workspace_snapshot',
    {
      title: 'Get workspace snapshot',
      description: 'Use this when the user asks for the current Teams workspace tasks or active Codex jobs. This is a deterministic read-only data tool; it never invents an LLM answer.',
      inputSchema: workspaceInputSchema,
      outputSchema: GenUiEnvelopeV1BaseSchema,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        openWorldHint: false,
        idempotentHint: true,
      },
      _meta: { ui: { visibility: ['model'] } },
    },
    async ({ limit }) => {
      const envelope = workspaceEnvelope(options, limit ?? 8);
      return resultForEnvelope(envelope, fallbackTextOf(envelope));
    },
  );

  registerAppTool(
    server,
    'get_weather',
    {
      title: 'Get weather',
      description: 'Use this when the user supplies device coordinates or explicitly provided coordinates and asks for current weather. Do not infer GPS, a city, or a default location in this tool.',
      inputSchema: weatherInputSchema,
      outputSchema: GenUiEnvelopeV1BaseSchema,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        openWorldHint: true,
        idempotentHint: true,
      },
      _meta: { ui: { visibility: ['model'] } },
    },
    async ({ latitude, longitude, demo }) => {
      try {
        const weather = await options.getWeather(latitude, longitude, { demo });
        const envelope = weatherEnvelope(weather);
        return resultForEnvelope(envelope, fallbackTextOf(envelope));
      } catch (error) {
        const message = error instanceof Error ? error.message : '날씨 정보를 가져오지 못했습니다.';
        return errorResult(`날씨 조회에 실패했습니다. 위치와 네트워크를 확인하세요. (${message})`);
      }
    },
  );

  registerAppTool(
    server,
    'get_job_status',
    {
      title: 'Get Codex job status',
      description: 'Use this when the user asks for a Codex job status. If jobId is omitted, return a deterministic list of recent jobs.',
      inputSchema: jobInputSchema,
      outputSchema: GenUiEnvelopeV1BaseSchema,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        openWorldHint: false,
        idempotentHint: true,
      },
      _meta: { ui: { visibility: ['model'] } },
    },
    async ({ jobId, limit }) => {
      const selected = jobId
        ? options.agentService.getLocalOnly(jobId)
        : options.agentService.listLocalOnly(limit ?? 8)[0];
      const envelope = jobEnvelope(selected, limit ?? 8);
      return resultForEnvelope(envelope, fallbackTextOf(envelope));
    },
  );

  registerAppTool(
    server,
    'render_workspace_response',
    {
      title: 'Render workspace response',
      description: 'Use this after a data tool has produced a GenUiEnvelopeV1 when the user needs the read-only MCP App view. It only renders supplied structured data, never calls an LLM or fetches hidden data, and rejects every envelope action (including feedback); interactive actions belong to the Teams host.',
      inputSchema: renderInputSchema,
      outputSchema: GenUiEnvelopeV1BaseSchema,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        openWorldHint: false,
        idempotentHint: true,
      },
      _meta: {
        ui: {
          resourceUri: MCP_GENUI_RESOURCE_URI,
          visibility: ['model'],
        },
      },
    },
    async ({ envelope }) => {
      const parsed = GenUiEnvelopeV1Schema.safeParse(envelope);
      if (!parsed.success) {
        return errorResult('render_workspace_response에는 유효한 GenUiEnvelopeV1이 필요합니다. 데이터 도구를 먼저 호출하세요.');
      }

      if (parsed.data.actions.length > 0) {
        return errorResult('MCP GenUI 위젯은 읽기 전용입니다. action 또는 feedback이 포함된 envelope는 Teams 호스트에서만 렌더링할 수 있습니다.');
      }

      return resultForEnvelope(parsed.data, fallbackTextOf(parsed.data));
    },
  );
}

export function createMcpGenUiServer(options: McpGenUiServerOptions): McpGenUiServerInstance {
  const server = new McpServer(
    {
      name: options.serverName ?? 'teams-workspace-mcp',
      version: options.serverVersion ?? '1.0.0',
    },
    {
      instructions: 'This MCP App renders structured workspace data in a read-only widget. render_workspace_response rejects every envelope action, including feedback; interactive actions must be handled by the Teams host. It is not the Teams mobile iframe and cannot read Teams GPS directly.',
    },
  );

  registerTools(server, options);

  registerAppResource(
    server,
    'Teams Workspace GenUI',
    MCP_GENUI_RESOURCE_URI,
    {
      description: 'Portable read-only MCP Apps widget for rendering action-free GenUiEnvelopeV1 data. This resource is for MCP hosts such as ChatGPT or Codex, not the Teams mobile tab iframe; interactive actions are rejected by render_workspace_response.',
      mimeType: MCP_GENUI_RESOURCE_MIME_TYPE,
      _meta: {
        ui: {
          prefersBorder: false,
          csp: { connectDomains: [], resourceDomains: [] },
        },
      },
    },
    async (uri) => ({
      contents: [{
        uri: uri.toString(),
        mimeType: RESOURCE_MIME_TYPE,
        text: await resolveWidgetHtml(options),
        _meta: {
          ui: {
            prefersBorder: false,
            csp: { connectDomains: [], resourceDomains: [] },
          },
        },
      }],
    }),
  );

  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: options.sessionMode === 'stateless' ? undefined : () => randomUUID(),
    enableJsonResponse: options.enableJsonResponse,
    onsessioninitialized: options.onSessionInitialized,
    onsessionclosed: options.onSessionClosed,
  });
  const ready = server.connect(transport);
  let closePromise: Promise<void> | undefined;

  return {
    server,
    transport,
    ready,
    async close(): Promise<void> {
      if (!closePromise) {
        closePromise = (async () => {
          await transport.close().catch(() => undefined);
          await server.close().catch(() => undefined);
        })();
      }
      await closePromise;
    },
  };
}

type Session = McpGenUiServerInstance;

type SessionEntry = {
  session: Session;
  sessionId?: string;
  lastActivity: number;
  inFlight: number;
  initializing: boolean;
  closed: boolean;
  closeNotified: boolean;
  closePromise?: Promise<void>;
};

function positiveIntegerOption(value: number | undefined, fallback: number, name: string): number {
  const candidate = value ?? fallback;
  if (!Number.isFinite(candidate) || candidate <= 0) {
    throw new RangeError(`${name} must be a positive finite number`);
  }
  return Math.max(1, Math.floor(candidate));
}

function isInitializeRequestBody(body: unknown): boolean {
  const message = Array.isArray(body)
    ? body.length === 1 ? body[0] : undefined
    : body;
  if (!message || typeof message !== 'object' || Array.isArray(message)) return false;
  return (message as { method?: unknown }).method === 'initialize';
}

export function createMcpGenUiHandler(options: McpGenUiServerOptions): RequestHandler & { close(): Promise<void> } {
  const sessions = new Map<string, SessionEntry>();
  const stateful = options.sessionMode !== 'stateless';
  const transientSessions = new Set<SessionEntry>();
  const entries = new Set<SessionEntry>();
  const sessionTtlMs = positiveIntegerOption(options.sessionTtlMs, 10 * 60 * 1000, 'sessionTtlMs');
  const maxSessions = positiveIntegerOption(options.maxSessions, 64, 'maxSessions');
  const sessionSweepIntervalMs = positiveIntegerOption(
    options.sessionSweepIntervalMs,
    Math.min(sessionTtlMs, 60 * 1000),
    'sessionSweepIntervalMs',
  );
  let sweepPromise: Promise<void> | undefined;
  let closed = false;
  let closePromise: Promise<void> | undefined;

  const removeEntry = (entry: SessionEntry): void => {
    if (entry.sessionId && sessions.get(entry.sessionId) === entry) {
      sessions.delete(entry.sessionId);
    }
    transientSessions.delete(entry);
    entries.delete(entry);
  };

  const closeEntry = (entry: SessionEntry): Promise<void> => {
    if (entry.closePromise) return entry.closePromise;

    entry.closed = true;
    removeEntry(entry);
    let resolveClose!: () => void;
    let rejectClose!: (error: unknown) => void;
    entry.closePromise = new Promise<void>((resolve, reject) => {
      resolveClose = resolve;
      rejectClose = reject;
    });
    void (async () => {
      try {
        await entry.session.close();
        if (entry.sessionId && !entry.closeNotified) {
          entry.closeNotified = true;
          await options.onSessionClosed?.(entry.sessionId);
        }
        resolveClose();
      } catch (error) {
        rejectClose(error);
      }
    })();
    return entry.closePromise;
  };

  const sweepIdleSessions = async (): Promise<void> => {
    if (!stateful || closed || sweepPromise) return;
    sweepPromise = (async () => {
      const now = Date.now();
      const idle = [...entries].filter((entry) =>
        !entry.closed
        && entry.inFlight === 0
        && now - entry.lastActivity >= sessionTtlMs,
      );
      await Promise.allSettled(idle.map((entry) => closeEntry(entry)));
    })();
    try {
      await sweepPromise;
    } finally {
      sweepPromise = undefined;
    }
  };

  const sweepTimer = stateful
    ? setInterval(() => {
      void sweepIdleSessions();
    }, sessionSweepIntervalMs)
    : undefined;
  sweepTimer?.unref?.();

  const close = (): Promise<void> => {
    if (closePromise) return closePromise;
    closed = true;
    if (sweepTimer) clearInterval(sweepTimer);
    const current = [...entries];
    closePromise = Promise.allSettled(current.map((entry) => closeEntry(entry))).then(() => undefined);
    return closePromise;
  };

  const handler: RequestHandler = async (request, response) => {
    const sessionId = request.header('mcp-session-id');
    const method = request.method.toUpperCase();

    if (!stateful) {
      if (method !== 'POST') {
        response.status(sessionId ? 404 : 400).json({
          error: sessionId ? 'Unknown MCP session' : 'MCP session is required for this method',
        });
        return;
      }

      let session: Session | undefined;
      try {
        session = createMcpGenUiServer(options);
        await session.ready;
        await session.transport.handleRequest(request, response, request.body);
      } catch (error) {
        if (!response.headersSent) {
          const message = error instanceof Error ? error.message : 'MCP request failed';
          response.status(500).json({ error: message });
        }
      } finally {
        if (session) await session.close();
      }
      return;
    }

    let entry: SessionEntry | undefined;
    if (sessionId) {
      entry = sessions.get(sessionId);
      if (!entry) {
        response.status(404).json({ error: 'Unknown MCP session' });
        return;
      }
    } else if (method === 'POST' && isInitializeRequestBody(request.body)) {
      if (closed) {
        response.status(503).json({ error: 'MCP router is closing' });
        return;
      }
      if (entries.size >= maxSessions) {
        response.status(503).json({ error: 'MCP session limit reached' });
        return;
      }

      let created: Session | undefined;
      const serverOptions: McpGenUiServerOptions = {
        ...options,
        onSessionInitialized: async (initializedId) => {
          if (!entry || entry.closed) throw new Error('MCP session was closed during initialization');
          entry.sessionId = initializedId;
          sessions.set(initializedId, entry);
          transientSessions.delete(entry);
          try {
            await options.onSessionInitialized?.(initializedId);
          } catch (error) {
            await closeEntry(entry);
            throw error;
          }
        },
        onSessionClosed: async (closedId) => {
          const current = sessions.get(closedId);
          if (current) {
            await closeEntry(current);
            return;
          }
          await options.onSessionClosed?.(closedId);
        },
      };

      try {
        created = createMcpGenUiServer(serverOptions);
        entry = {
          session: created,
          lastActivity: Date.now(),
          inFlight: 0,
          initializing: true,
          closed: false,
          closeNotified: false,
        };
        entries.add(entry);
        transientSessions.add(entry);
        created.transport.onclose = () => {
          void closeEntry(entry!).catch(() => undefined);
        };
        created.transport.onerror = () => {
          if (entry && (entry.initializing || !entry.sessionId)) {
            void closeEntry(entry).catch(() => undefined);
          }
        };
        await created.ready;
      } catch (error) {
        if (entry) await closeEntry(entry).catch(() => undefined);
        if (!response.headersSent) {
          const message = error instanceof Error ? error.message : 'MCP session initialization failed';
          response.status(500).json({ error: message });
        }
        return;
      }
    } else {
      response.status(400).json({ error: 'MCP session is required for this method' });
      return;
    }

    if (!entry || entry.closed) {
      response.status(404).json({ error: 'Unknown MCP session' });
      return;
    }
    entry.lastActivity = Date.now();
    entry.inFlight += 1;
    const initializationRequest = method === 'POST' && isInitializeRequestBody(request.body);
    try {
      await entry.session.transport.handleRequest(request, response, request.body);
    } catch (error) {
      if (!response.headersSent) {
        const message = error instanceof Error ? error.message : 'MCP request failed';
        response.status(500).json({ error: message });
      }
    } finally {
      entry.inFlight -= 1;
      entry.initializing = false;
      if (initializationRequest && response.statusCode >= 400) {
        await closeEntry(entry).catch(() => undefined);
      }
    }
  };

  return Object.assign(handler, { close });
}

export function createMcpGenUiRouter(options: McpGenUiServerOptions): McpGenUiRouter {
  const router = express.Router() as McpGenUiRouter;
  const handler = createMcpGenUiHandler(options);
  router.use(express.json({ limit: '1mb' }));
  router.all('/', handler);
  router.close = handler.close;
  return router;
}
