import assert from 'node:assert/strict';
const module = await import('../src/client/job-deep-link.js').catch(() => ({}));
assert.equal(typeof module.parseRequestedJobId, 'function', 'personal tab must resolve a requested job hint');
assert.equal(module.parseRequestedJobId('?jobId=task-a'), 'task-a');
assert.equal(module.parseRequestedJobId('', 'task-b'), 'task-b');
assert.equal(module.parseRequestedJobId('?jobId=task-a', 'task-a'), 'task-a');
assert.equal(module.parseRequestedJobId('?jobId=task-a', 'copilot-ui:task-a'),'task-a');
assert.equal(module.parseRequestedCopilotJobId('', 'copilot-ui:task-a'),'task-a');
assert.equal(module.parseRequestedCopilotJobId('?jobId=task-a&view=copilot'),'task-a');
assert.equal(module.parseRequestedCopilotJobId('?jobId=task-a&view=core','copilot-ui:task-a'),undefined,'return link must not loop back to SDK');
assert.equal(module.parseRequestedCopilotJobId('?jobId=task-b&view=copilot','copilot-ui:task-a'),undefined,'conflicting navigation hints are rejected');
assert.equal(module.parseRequestedJobId('?jobId=task-a', 'task-b'), undefined);
assert.equal(module.parseRequestedJobId('?jobId=task-a&jobId=task-b'), undefined);
for (const id of ['../other', '', 'task a', 'x'.repeat(201)]) assert.equal(module.parseRequestedJobId(`?jobId=${encodeURIComponent(id)}`), undefined);
let reads = 0;
const job = { id: 'task-a', result: 'authorized result' };
assert.equal(await module.loadRequestedJob('task-a', { getJob: async (id: string) => { reads++; assert.equal(id, 'task-a'); return job; } }), job);
assert.equal(reads, 1);
await assert.rejects(() => module.loadRequestedJob('task-foreign', { getJob: async () => { throw new Error('403 forbidden'); } }), /403/);
console.log('PASS: job deep links are hints only, reject ambiguity, and require an authorized detail read');
assert.equal(typeof module.includeRequestedJob, 'function', 'an authorized older job must appear in the visible job list');
const listed = [{ id: 'task-newer' }];
assert.deepEqual(module.includeRequestedJob(listed, job), [job, ...listed]);
assert.deepEqual(listed, [{ id: 'task-newer' }], 'list response must not be mutated');
assert.deepEqual(module.includeRequestedJob([job], job), [job], 'requested job is not duplicated');
