import assert from 'node:assert/strict';
import { createCoreOrchestrationClient } from '../src/client/core-orchestration-client.js';
import * as conversationModule from '../src/client/job-conversation.js';
import type { CoreOrchestrationJob } from '../src/shared/core-orchestration.js';

const parent = { id: 'task-parent', prompt: '첫 요청', status: 'completed', mode: 'read-only', result: '첫 응답', progress: [], createdAt: '2026-10-06T00:00:00Z', threadId: 'private-thread' } as CoreOrchestrationJob;
const child = { ...parent, id: 'task-child', parentJobId: parent.id, prompt: '이어가기 Authorization: Bearer secret-token', result: '<script>not HTML</script>', createdAt: '2026-10-06T00:01:00Z' };
const rows = new Map([[parent.id, parent], [child.id, child]]);
const requests: string[] = [];
const client = createCoreOrchestrationClient(async (path) => {
  requests.push(path);
  const row = rows.get(decodeURIComponent(path.split('/').at(-1)!));
  return new Response(JSON.stringify(row ? { job: row } : { error: { code: 'CORE_ORCHESTRATION_NOT_FOUND' } }), { status: row ? 200 : 404, headers: { 'content-type': 'application/json' } });
});
assert.equal(typeof client.getJobConversation, 'function', 'history must expose the selected owner-visible conversation');
const history = await client.getJobConversation!(child.id);
assert.deepEqual(history.conversation.turns.map(turn => turn.jobId), [parent.id, child.id]);
assert.deepEqual(history.conversation.turns.map(turn => turn.response), ['첫 응답', '<script>not HTML</script>']);
assert.doesNotMatch(JSON.stringify(history.conversation), /private-thread|secret-token/);
assert.match(history.conversation.turns[1].request, /REDACTED/);
assert.equal(history.conversation.complete, true);
assert.deepEqual(requests, ['/api/core-orchestration/jobs/task-child', '/api/core-orchestration/jobs/task-parent']);
rows.delete(parent.id);
const unavailable = await client.getJobConversation!(child.id);
assert.equal(unavailable.conversation.complete, false);
assert.equal(unavailable.conversation.unavailableReason, 'previous-turn-unavailable');
assert.deepEqual(unavailable.conversation.turns.map(turn => turn.jobId), [child.id]);
rows.set(parent.id, { ...parent, parentJobId: child.id });
const cyclic = await client.getJobConversation!(child.id);
assert.equal(cyclic.conversation.complete, false);
assert.equal(cyclic.conversation.unavailableReason, 'invalid-chain');
rows.set(parent.id, { ...parent, threadId: 'other-thread' });
const mismatched = await client.getJobConversation!(child.id);
assert.deepEqual(mismatched.conversation.turns.map(turn => turn.jobId), [child.id]);
assert.equal(mismatched.conversation.unavailableReason, 'invalid-chain');
await assert.rejects(client.getJobConversation!('unknown'), /오케스트레이션/);
assert.equal(typeof conversationModule.refreshVisibleJobConversation, 'function', 'polling must refresh the visible selected turn');
const refreshed = conversationModule.refreshVisibleJobConversation(history.conversation, { ...child, result: '최종 응답 password=secret-value', status: 'completed' });
assert.match(refreshed.turns[1].response!, /최종 응답/);
assert.doesNotMatch(JSON.stringify(refreshed), /secret-value/);
assert.equal(refreshed.turns[0], history.conversation.turns[0]);
assert.equal(conversationModule.refreshVisibleJobConversation(history.conversation, parent), history.conversation);
console.log('PASS: owner-visible turns use existing authenticated detail API, bound chains, redact credentials and mark missing history');
