import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
const module = await import('../src/server/personal-notification.js');
assert.equal(typeof module.PersonalNotificationBroker, 'function');
const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'teams-personal-notification-'));
try {
  const file = path.join(directory, 'state.json');
  const tenantId = '32441482-5adf-4438-8a8f-0e15f33b77f1', requesterId = 'e30915e5-3407-406d-bd1c-4495d163d618';
  const principal = { tenantId, requesterId };
  const botId = 'e915b402-eed4-4ee2-ba1f-c31d75c870a5';
  const { deriveServerOwnedRestConversationId } = await import('../src/server/rest-scope.js');
  const job = { id: 'task-synthetic', ...principal, conversationId: deriveServerOwnedRestConversationId(principal), status: 'completed', prompt: '합성 요청', result: '합성 결과', progress: [], mode: 'read-only', createdAt: new Date().toISOString(), durableNotifications: { enabled: true, delivered: [] } } as any;
  const event = { job, conversationId: job.conversationId, kind: 'result', phase: 'completed', message: '합성 결과' } as any;
  const sends: string[] = [];
  let broker = new module.PersonalNotificationBroker(file, botId, async (target: string) => { sends.push(target); return { state: 'accepted', activityId: 'activity-synthetic' }; });
  await broker.initialize();
  await broker.deliver(event);
  assert.equal(broker.status(job.id, principal)?.state, 'waiting-personal-chat');
  assert.deepEqual(sends, [], 'never send a REST ID');
  const activity = { channelId: 'msteams', from: { aadObjectId: requesterId }, recipient: { id: `28:${botId}` }, conversation: { id: 'personal-synthetic', tenantId, conversationType: 'personal' }, serviceUrl: 'https://smba.trafficmanager.net/teams/' };
  assert.equal(await broker.observeAuthenticatedActivity({ ...activity, conversation: { ...activity.conversation, conversationType: 'groupChat' } }), false);
  assert.equal(await broker.observeAuthenticatedActivity({ ...activity, from: { id: requesterId } }), false, 'no fallback identity binding');
  assert.equal(await broker.observeAuthenticatedActivity({ ...activity, recipient: { id: 'other-bot' } }), false);
  assert.equal(await broker.observeAuthenticatedActivity(activity), true);
  await broker.flush();
  assert.deepEqual(sends, ['personal-synthetic']);
  assert.equal(broker.status(job.id, principal)?.state, 'accepted');
  assert.equal(broker.status(job.id, { ...principal, requesterId: 'other-owner' }), undefined);
  await broker.deliver(event);
  assert.equal(sends.length, 1, 'duplicate event must not send twice');
  broker = new module.PersonalNotificationBroker(file, botId, async () => { throw new Error('must not resend accepted after restart'); });
  await broker.initialize(); await broker.flush();
  assert.equal(broker.status(job.id, principal)?.state, 'accepted');
  await broker.deliver({ ...event, job: { ...job, id: 'task-silent', durableNotifications: { enabled: false, delivered: [] } } });
  assert.equal(broker.status('task-silent', principal), undefined);
  await broker.deliver({ ...event, job: { ...job, id: 'task-legacy', durableNotifications: undefined } });
  assert.equal(broker.status('task-legacy', principal), undefined, 'legacy missing intent never enables new personal delivery');
  const otherTenant = '32441482-5adf-4438-8a8f-0e15f33b77f2';
  const otherPrincipal = { ...principal, tenantId: otherTenant };
  await broker.deliver({ ...event, conversationId: deriveServerOwnedRestConversationId(otherPrincipal), job: { ...job, ...otherPrincipal, id: 'task-other-tenant', conversationId: deriveServerOwnedRestConversationId(otherPrincipal) } });
  assert.equal(broker.status('task-other-tenant', otherPrincipal)?.state, 'waiting-personal-chat');
  const uncertain = new module.PersonalNotificationBroker(file, botId, async () => ({ state: 'ambiguous' }));
  await uncertain.initialize(); await uncertain.deliver({ ...event, job: { ...job, id: 'task-uncertain' } });
  assert.equal(uncertain.status('task-uncertain', principal)?.state, 'ambiguous');
  await uncertain.flush();
  assert.equal(uncertain.status('task-uncertain', principal)?.state, 'ambiguous', 'uncertain sends never auto retry');
  const persisted = JSON.parse(await fs.readFile(file, 'utf8'));
  persisted.outbox.find((entry: any) => entry.jobId === 'task-uncertain').receipt.state = 'sending';
  await fs.writeFile(file, JSON.stringify(persisted));
  const recovered = new module.PersonalNotificationBroker(file, botId, async () => { throw new Error('must not retry interrupted send'); });
  await recovered.initialize(); await recovered.flush();
  assert.equal(recovered.status('task-uncertain', principal)?.state, 'ambiguous');
  console.log('PASS: verified owner personal binding, durable pending/receipt, notify:false, restart and ambiguous no-resend');
} finally { await fs.rm(directory, { recursive: true, force: true }); }
